'use client';

import { useEffect, useState } from 'react';
import { Edit2, Loader2, Plus, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { InventoryService } from '@/services/inventory-service';
import { toast } from '@/hooks/use-toast';

export default function SuppliersPage() {
  const [rows, setRows] = useState<any[]>([]); const [editing, setEditing] = useState<any>(null); const [form, setForm] = useState({ name: '', phone: '', address: '' }); const [search, setSearch] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { try { setRows(await InventoryService.getSuppliers()); } catch (error) { toast({ variant: 'destructive', title: 'فشل تحميل الموردين', description: String(error) }); } };
  useEffect(() => { load(); }, []);
  const save = async () => { if (!form.name.trim()) return; setSaving(true); try { const user = JSON.parse(localStorage.getItem('dubsar_session') || '{}'); if (editing) await InventoryService.updateSupplier(editing.id, form, user); else await InventoryService.createSupplier(form, user); setEditing(null); setForm({ name: '', phone: '', address: '' }); await load(); toast({ title: 'تم حفظ بيانات المورد بنجاح' }); } catch (error) { toast({ variant: 'destructive', title: 'فشل حفظ المورد', description: String(error) }); } finally { setSaving(false); } };
  const filtered = rows.filter((row) => `${row.name} ${row.phone || ''}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-6" dir="rtl"><div className="flex justify-between items-end"><div><h1 className="text-3xl font-black">الموردون</h1><p className="text-sm font-bold text-muted-foreground">سجل الموردين والأرصدة والذمم المالية</p></div><Button onClick={() => { setEditing(null); setForm({ name: '', phone: '', address: '' }); }} className="gap-2 font-black"><Plus className="h-4 w-4" />مورد جديد</Button></div><div className="rounded-xl border bg-white p-4 grid grid-cols-1 md:grid-cols-4 gap-3 items-end"><div><Label>الاسم</Label><Input className="mt-2" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></div><div><Label>الهاتف</Label><Input className="mt-2" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></div><div><Label>العنوان</Label><Input className="mt-2" value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} /></div><Button disabled={saving} onClick={save} className="gap-2 font-black">{saving ? <Loader2 className="animate-spin" /> : <Save className="h-4 w-4" />}{editing ? 'حفظ التعديل' : 'حفظ المورد'}</Button></div><Input placeholder="بحث بالاسم أو الهاتف" value={search} onChange={(event) => setSearch(event.target.value)} className="max-w-md" /><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-muted/40"><tr><th className="p-4 text-right">المورد</th><th className="p-4 text-right">الهاتف</th><th className="p-4 text-right">الذمة</th><th /></tr></thead><tbody>{filtered.map((row) => <tr key={row.id} className="border-t"><td className="p-4 font-black">{row.name}</td><td className="p-4">{row.phone || '-'}</td><td className="p-4 font-black text-red-600">{Number(row.balance || 0).toLocaleString()} د.ع</td><td className="p-4"><Button size="icon" variant="ghost" onClick={() => { setEditing(row); setForm({ name: row.name, phone: row.phone || '', address: row.address || '' }); }}><Edit2 className="h-4 w-4" /></Button></td></tr>)}</tbody></table></div></div>;
}
